Repository OData/odata.net, pull requests merged in 2020-09, with the labels that each got.

#1793 different null validation messages for complex and primitive collections
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/ReaderValidationUtils.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/NavigationPropertyOnComplexTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/CollectionValueReaderJsonLightTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/PropertyReaderJsonLightTests.cs
Labels: Ready for review

#1880 downgrade the System.Text.Json package reference version
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
Labels: Ready for review

#1886 Bugfix/headers should be case insensitive
  src/Microsoft.OData.Core/Batch/ODataBatchOperationHeaders.cs
  src/Microsoft.OData.Core/ODataAsynchronousResponseMessage.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/ODataMessageConcreteTypePreferHeaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/InMemoryMessage.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataPreferenceHeaderTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/Batch/BatchReaderHeadersTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/Batch/BatchReaderStreamProcessPartHeaderTests.cs
Labels: Ready for review

#1887 Fix issue #1883, MultipartMixed grows cache indefinitely
  src/Microsoft.OData.Core/MediaTypeUtils.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/MediaTypeUtilsTests.cs
Labels: P1, Ready for review, performance

#1888 Performance fixes
  src/Microsoft.OData.Core/Evaluation/ODataMetadataContext.cs
  src/Microsoft.OData.Core/Metadata/MetadataUtils.cs
  src/Microsoft.OData.Edm/ExtensionMethods/EdmTypeSemantics.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  src/Microsoft.OData.Edm/Schema/EdmModelBase.cs
Labels: performance
