Repository OData/odata.net, pull requests merged in 2020-02, with the labels that each got.

#1664 Fixing issue #843
  src/Microsoft.OData.Client/BaseSaveResult.cs
  src/Microsoft.OData.Client/DataServiceRequest.cs
  src/Microsoft.OData.Client/Materialization/HttpWebResponseMessage.cs
  src/Microsoft.OData.Client/Util.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientQueryTests.cs
Labels: Ready for review, docs-needed

#1677 #1676 Fixed IncludeInServiceDocument overload for Container.AddEntity…
  src/Microsoft.OData.Edm/Schema/EdmEntitySet.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Schema/EdmEntityContainerTests.cs
Labels: Ready for review

#1614 Fix DataServiceContext can't work with POCO's due to Missing IEdmModel
  src/Microsoft.OData.Client/DataServiceClientFormat.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/Microsoft.OData.Core.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/packages.config
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/DataServiceContextUtil.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ClientPropertyTrackingTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ClientSerializerTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/CustomizedHttpWebRequestMessage.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceClientFormatTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceContextTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceRequestTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ODataMessageReadingHelperTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ODataMessageWritingHelperTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Serialization/ODataWriterWrapperUnitTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/T4/ODataT4CamelCaseTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ClientCSharpRegressionTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ClientErrorHandlingShortIntegrationTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ClientShortIntegrationRegressionTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/ClientRegressionTests.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/EntitySetResolverTests.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/StateManagementTests.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/UpdateTests.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/VersionedRequests.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/medialinkentries.vb
Labels: docs-needed
