Repository OData/odata.net, pull requests merged in 2021-04, with the labels that each got.

#2022 Fix/2005 translate path select item
  src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
Labels: Ready for review, Small

#2030 Implement asynchronous support in ODataJsonLightSerializer
  src/Microsoft.OData.Core/ContainerBuilderExtensions.cs
  src/Microsoft.OData.Core/Json/JsonLightInstanceAnnotationWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightSerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightValueSerializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonLightInstanceAnnotationWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerAsyncTests.cs
Labels: Extra Large, Ready for review

#2046 Implement asynchronous support in ODataJsonLightCollectionSerializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionSerializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionSerializerTests.cs
Labels: Medium, Ready for review

#2048 Implement asynchronous support in ODataJsonLightServiceDocumentSerializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightServiceDocumentSerializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightServiceDocumentSerializerTests.cs
Labels: Medium, Ready for review

#2050 Implement asynchronous support in ODataJsonLightEntityReferenceLinkSerializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightEntityReferenceLinkSerializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntityReferenceLinkSerializerTests.cs
Labels: Medium, Ready for review

#1806 Sequencing Json Batch requests with the dependsOn property
  src/Microsoft.OData.Client/BatchSaveResult.cs
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/Descriptor.cs
  src/Microsoft.OData.Client/ODataRequestMessageWrapper.cs
  test/EndToEndTests/Tests/Client/AsynchronousTests/AsyncMethodTests.cs
Labels: Medium

#2055 Add support for Singleton's in VocabularyAnnotationInaccessibleTarget
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs
  src/Microsoft.OData.Edm/Validation/ValidationRules.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRulesTests.cs
Labels: Medium

#2052 Implement asynchronous support in ODataJsonLightResourceSerializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceSerializer.cs
  src/Microsoft.OData.Core/ODataResourceSetBase.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonLightInstanceAnnotationWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntityReferenceLinkSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerAsyncTests.cs
Labels: Extra Large, Ready for review

#2053 Elide async and await in pass-through asynchronous methods
  src/Microsoft.OData.Core/Json/JsonValueUtilsAsync.cs
  src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
  src/Microsoft.OData.Core/Json/NonIndentedTextWriter.cs
  src/Microsoft.OData.Core/Json/ODataJsonTextWriter.cs
  src/Microsoft.OData.Core/Json/TextWriterWrapper.cs
  src/Microsoft.OData.Core/ODataBinaryStreamWriter.cs
Labels: Medium

#2017 Issues #2016, #1447: In-operator precedence
  src/Microsoft.OData.Core/UriParser/Parsers/UriQueryExpressionParser.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceQueryProviderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/SelectExpandParserTests.cs
Labels: Ready for review

#2051 Add support for $count in navigation properties
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
  src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandTermParser.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/ExpandedCountSelectItem.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
Labels: Ready for review, Small
