Repository OData/odata.net, pull requests merged in 2021-08, with the labels that each got.

#2136 Tests to verify congruence between synchronous and asynchronous APIs exposed by RawOutputContext class
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataRawOutputContextApiTests.cs
Labels: Medium

#2142 Tests to verify congruence between synchronous and asynchronous APIs exposed by ODataMultipartMixedBatchOutputContext class
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMultipartMixedBatchOutputContextApiTests.cs
Labels: Extra Large

#2155 Fix AggregateException thrown by OData writers async API
  src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs
  src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
  src/Microsoft.OData.Core/ODataParameterWriterCore.cs
  src/Microsoft.OData.Core/ODataRawOutputContext.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
Labels: Ready for review, Large

#2144 Skip string allocation for keys of PropertyCache
  src/Microsoft.OData.Core/PropertyCache.cs
  src/Microsoft.OData.Core/PropertyCacheHandler.cs
Labels: Extra Small

#2139 Fix escape function binding type constraint
  src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
Labels: Medium

#2146 Tests to verify congruence between synchronous and asynchronous APIs exposed by ODataJsonLightOutputContext class
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightOutputContextApiTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightOutputContextTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/TestODataJsonLightWriterResourceState.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/TestODataResourceMetadataBuilder.cs
Labels: Ready for review, Medium

#2156 Fix string allocation performance issue for IsQualifiedName
  src/Microsoft.OData.Edm/EdmUtil.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/EdmUtilTests.cs
Labels: Extra Small

#2154 Skip lambda allocation in FindTransientAnnotation
  src/Microsoft.OData.Edm/GlobalSuppressions.cs
  src/Microsoft.OData.Edm/VersioningList.cs
  src/Microsoft.OData.Edm/Vocabularies/Annotations/EdmDirectValueAnnotationsManager.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/VersioningListTests.cs
Labels: Medium

#2161 Update baseline
  test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
  test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj
Labels: Extra Large
