Repository OData/odata.net, pull requests merged in 2021-06, with the labels that each got.

#2097 Fix/2094 Add cancellation token to ExecuteAsync in DataServiceActionQuery and DataServiceActionQueryofT
  src/Microsoft.OData.Client/DataServiceActionQuery.cs
  src/Microsoft.OData.Client/DataServiceActionQueryOfT.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/CancellationTokenTests.cs
Labels: Extra Small

#2078 Implement asynchronous support in ODataJsonLightWriter
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriterCoreTests.cs
Labels: Extra Large, Ready for review

#2096 Implement asynchronous support for ODataJsonLightParameterWriter
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterWriter.cs
  src/Microsoft.OData.Core/ODataParameterWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs
Labels: Large

#2110 ODataNotificationWriter and ODataNotificationStream wrapper classes should not dispose the passed TextWriter and Stream respectively
  src/Microsoft.OData.Core/ODataNotificationStream.cs
  src/Microsoft.OData.Core/ODataNotificationWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationStreamTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationWriterTests.cs
Labels: Extra Small

#2082 Implement asynchronous support in ODataJsonLightDeltaWriter
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeltaWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
Labels: Medium, Ready for review

#2109 Implement asynchronous support in ODataWriteStream
  src/Microsoft.OData.Core/ODataStream.cs
  src/Microsoft.OData.Core/ODataWriteStream.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriteStreamTests.cs
Labels: Medium, Ready for review

#2072 no error message when reading an incorrect structure of a collection …
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/FeedReaderJsonLightTests.cs
Labels: Extra Small
