Repository OData/odata.net, pull requests merged in 2021-07, with the labels that each got.

#2111 Implement asynchronous support in ODataJsonLightBatchWriter
  src/Microsoft.OData.Core/Batch/ODataBatchUtils.cs
  src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
  src/Microsoft.OData.Core/GlobalSuppressions.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchWriter.cs
  src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchWriterTests.cs
Labels: Extra Large, Ready for review

#2121 Implement asynchronous support in RawValueWriter
  src/Microsoft.OData.Core/RawValueWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/RawValueWriterTests.cs
Labels: Small

#2041 Remember the SelectItem instances that are thrown away because of the existence of a WildcardSelectItem
  src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
  src/Microsoft.OData.Core/UriParser/Binders/SelectExpandClauseFinisher.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/SelectExpandClause.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/WildcardSelectItem.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/SelectExpandBinderTests.cs
Labels: Ready for review, Small

#2021 HttpClientRequestMessage: Fix UnwrapAggregateException.
  src/Microsoft.OData.Client/Serialization/HttpClientRequestMessage.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/HttpClientRequestMessageTests.cs
Labels: Extra Small, Ready for review

#2124 Implement asynchronous support in ODataAsynchronousWriter
  src/Microsoft.OData.Core/ODataAsynchronousResponseMessage.cs
  src/Microsoft.OData.Core/ODataAsynchronousWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataAsynchronousWriterTests.cs
Labels: Medium, Ready for review

#2125 Implement asynchronous support in ODataRawOutputContext
  src/Microsoft.OData.Core/ODataRawOutputContext.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataRawOutputContextTests.cs
Labels: Medium, Ready for review

#2126 Implement asynchronous support in ODataMultipartMixedBatchWriter
  src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
  src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs
  src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriterUtils.cs
  src/Microsoft.OData.Core/ODataWriteStream.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMultipartMixedBatchWriterTests.cs
Labels: Extra Large, Ready for review

#2114 Implement asynchronous support in ODataJsonLightOutputContext
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightOutputContextTests.cs
Labels: Extra Large, Ready for review

#2123 Fixed issue with caching of enumerable instead of list.
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsNavigationSource.cs
Labels: Extra Small

#2133 Cache annotation full qualified name in FindDeclaredVocabularyAnnotations
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsElement.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsModel.cs
Labels: Extra Small
