Repository OData/odata.net, pull requests merged in 2021-12, with the labels that each got.

#2257 FunctionCallBinder promotes arguments without checking return type
  src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/OpenPropertiesFunctionalTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/FunctionCallBinderTests.cs
Labels: Extra Small

#2256 Refactor alternate key resolver to avoid relying on exceptions
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/UriParser/Binders/CountSegmentBinder.cs
  src/Microsoft.OData.Core/UriParser/Parsers/CountSegmentParser.cs
  src/Microsoft.OData.Core/UriParser/Resolver/AlternateKeysODataUriResolver.cs
  src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs
  test/EndToEndTests/Framework/Core/Verification/StringResourceUtil.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientQueryTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/PathFunctionalTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/CaseInsensitiveResolverTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ExtensionTestBase.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ODataUriResolverTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/UnqualifiedODataUriResolverTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/CustomUriLiteralParserTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/CustomUriLiteralPrefixesTests.cs
Labels: Medium

#2264 Implement asynchronous support in BufferingJsonReader
  src/Microsoft.OData.Core/Json/BufferingJsonReader.cs
  src/Microsoft.OData.Core/Json/IJsonStreamReaderAsync.cs
  src/Microsoft.OData.Core/Json/JsonReader.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/BufferingJsonReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonReaderTests.cs
Labels: Extra Large

#2249 Perf results comparer
  tools/perf/PerfRegression.ps1
  tools/perf/ResultsComparer/Bdn/BdnComparer.cs
  tools/perf/ResultsComparer/Bdn/BdnModel.cs
  tools/perf/ResultsComparer/CommandLineOptions.cs
  tools/perf/ResultsComparer/Core/ComparerOptions.cs
  tools/perf/ResultsComparer/Core/ComparerResults.cs
  tools/perf/ResultsComparer/Core/IResultsComparer.cs
  tools/perf/ResultsComparer/Program.cs
  tools/perf/ResultsComparer/README.md
  tools/perf/ResultsComparer/ResultsComparer.csproj
  tools/perf/ResultsComparer/ResultsComparer.sln
  tools/perf/ResultsComparer/results.md
Labels: Large

#2216 #2132: Relative URIs for @oData.context are not supported
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
  src/Microsoft.OData.Core/ODataDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeserializerTests.cs
Labels: Extra Small
