Repository OData/odata.net, pull requests merged in 2021-09, with the labels that each got.

#2176 Fix pull request template such that referenced issue is linked and closed after pull request is merged
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Extra Small

#2178 Clone the reader setting when creating reader setting
  src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
Labels: Extra Small

#2130 Fix NullReferenceException thrown during materialization of lower-camel-cased payload
  src/Microsoft.OData.Client/ClientEdmModel.cs
  src/Microsoft.OData.Client/Common.cs
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
  src/Microsoft.OData.Client/TypeResolver.cs
  src/Microsoft.OData.Client/Util.cs
  src/Microsoft.OData.Client/WebUtil.cs
  src/Microsoft.OData.Edm/EdmUtil.cs
  src/Microsoft.Spatial/Util.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Tracking/DataServiceContextNoTrackingStreamsTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/CamelCasedTypeMaterializationTests.cs
Labels: Ready for review, Large

#2188 Avoid creating unused objects when calling ODataUri.Clone()
  src/Microsoft.OData.Core/Uri/ODataUri.cs
Labels: Extra Small

#2179 Fix the issue when read nested resource untyped in the request
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerUndeclaredTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
  test/FunctionalTests/Microsoft.OData.TestCommon/Microsoft.OData.TestCommon.csproj
  test/FunctionalTests/Microsoft.Spatial.Tests/Microsoft.Spatial.Tests.csproj
Labels: Small

#2160 Expand fully qualified type
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/ODataExpandPath.cs
  src/Microsoft.OData.Core/UriParser/UriEdmHelpers.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/ExpandBinderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataExpandPathTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathExtensionsTests.cs
Labels: Ready for review, Medium

#2193 Remove delegate allocation in ODataWriterCore.CheckForNestedResourceInfoWithContent()
  src/Microsoft.OData.Core/ODataWriterCore.cs
Labels: Extra Small

#2197 Reduce memory allocations from closures and lambdas
  README.md
  benchmarks.yml
  sln/OData.Tests.Performance.sln
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/SelectedPropertiesNode.cs
  src/Microsoft.OData.Core/WriterValidationUtils.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  test/PerformanceTests/SerializationBaselineTests/CharArrayPool.cs
  test/PerformanceTests/SerializationBaselineTests/DataModel.cs
  test/PerformanceTests/SerializationBaselineTests/DataSet.cs
  test/PerformanceTests/SerializationBaselineTests/FileSerializationBenchmarks.cs
  test/PerformanceTests/SerializationBaselineTests/IExperimentWriter.cs
  test/PerformanceTests/SerializationBaselineTests/InMemoryMessage.cs
  test/PerformanceTests/SerializationBaselineTests/InMemorySerializationBenchmarks.cs
  test/PerformanceTests/SerializationBaselineTests/JsonExperimentWriter.cs
  test/PerformanceTests/SerializationBaselineTests/ODataExperimentWriter.cs
  test/PerformanceTests/SerializationBaselineTests/ODataSyncExperimentWriter.cs
  test/PerformanceTests/SerializationBaselineTests/Program.cs
  test/PerformanceTests/SerializationBaselineTests/SerializationBaselineTests.csproj
Labels: Extra Large

#2187 Implement interfaces in support of asynchronous reading of OData message payloads
  src/Microsoft.OData.Core/Json/IJsonReaderAsync.cs
  src/Microsoft.OData.Core/Json/IJsonReaderFactoryAsync.cs
  src/Microsoft.OData.Core/Json/IJsonStreamReaderAsync.cs
  src/Microsoft.OData.Core/ODataBinaryStreamReader.cs
Labels: Extra Small
