Repository OData/odata.net, pull requests merged in 2021-05, with the labels that each got.

#2009 Enable EdmReference, EdmInclude vocabulary annotation
  src/Microsoft.OData.Edm/Csdl/CsdlJsonWriter.cs
  src/Microsoft.OData.Edm/Csdl/CsdlReader.Json.cs
  src/Microsoft.OData.Edm/Csdl/CsdlReader.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/Ast/CsdlInclude.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/Ast/CsdlIncludeAnnotations.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/Ast/CsdlModel.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/Ast/CsdlReferences.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/Common/XmlDocumentParser.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/CsdlDocumentParser.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/CsdlDocumentParserBase.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/CsdlJsonParser.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/CsdlReferenceParser.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/SchemaJsonParser.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsInclude.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsIncludeAnnotations.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsModel.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsReference.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaJsonWriter.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaWriter.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaXmlWriter.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelReferenceElementsJsonVisitor.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelReferenceElementsXmlVisitor.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  src/Microsoft.OData.Edm/Schema/Interfaces/IEdmInclude.cs
  src/Microsoft.OData.Edm/Schema/Interfaces/IEdmIncludeAnnotations.cs
  src/Microsoft.OData.Edm/Schema/Interfaces/IEdmReference.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderJsonTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Parsing/CsdlJsonParserTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/CsdlParsingTests.cs
Labels: Extra Large

#2035 in operator not working with null Guid values
  src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
Labels: Extra Small, Ready for review

#2058 Modify IODataOutputInStreamErrorListener interface to support asynchronous notifications when an in-stream error is to be written
  src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
  src/Microsoft.OData.Core/IODataOutputInStreamErrorListener.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeltaWriter.cs
  src/Microsoft.OData.Core/ODataAsynchronousWriter.cs
  src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
  src/Microsoft.OData.Core/ODataParameterWriterCore.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
Labels: Extra Small, Ready for review

#2075 Modify IODataStreamListener interface to support asynchronous notifications when the content stream of an operation has been disposed
  src/Microsoft.OData.Core/Batch/ODataBatchReader.cs
  src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
  src/Microsoft.OData.Core/IODataStreamListener.cs
  src/Microsoft.OData.Core/ODataReaderCore.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
Labels: Extra Small, Ready for review

#2069 Improve $count in $filter collection properties
  src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
  src/Microsoft.OData.Core/GlobalSuppressions.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/UriParser/Binders/CountSegmentBinder.cs
  src/Microsoft.OData.Core/UriParser/Binders/MetadataBinder.cs
  src/Microsoft.OData.Core/UriParser/ODataQueryOptionParser.cs
  src/Microsoft.OData.Core/UriParser/Parsers/CountSegmentParser.cs
  src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandOptionParser.cs
  src/Microsoft.OData.Core/UriParser/Parsers/UriParserHelper.cs
  src/Microsoft.OData.Core/UriParser/Parsers/UriQueryExpressionParser.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/CountNode.cs
  src/Microsoft.OData.Core/UriParser/SyntacticAst/CountSegmentToken.cs
  src/Microsoft.OData.Core/UriParser/SyntacticAst/QueryTokenKind.cs
  src/Microsoft.OData.Core/UriParser/Visitors/ISyntacticTreeVisitor.cs
  src/Microsoft.OData.Core/UriParser/Visitors/SyntacticTreeVisitor.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
Labels: Large, Ready for review

#2085 Add System.Runtime.CompilerServices.Unsafe and System.Text.Encodings.web dependency for OData.Edm
  src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec
  src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec
Labels: Extra Small

#1993 Perf fixes for ODL- Linq fixes
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/ODataUtils.cs
  src/Microsoft.OData.Core/SelectedPropertiesNode.cs
  src/Microsoft.OData.Core/UriParser/Binders/ExpandTreeNormalizer.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsElement.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsNavigationSource.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
Labels: Small

#1992 Client Perf improvement
  src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
  src/Microsoft.OData.Client/Metadata/ODataTypeInfo.cs
Labels: Large

#2087 Translate ExpandedCountSelectItem in BuildUri
  src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
  src/Microsoft.OData.Core/UriParser/Visitors/SelectItemTranslator.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
Labels: Extra Small, Ready for review

#2088 Update version to 7.9.0
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small

#2059 Implement asynchronous support in ODataJsonLightCollectionWriter
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionWriter.cs
  src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionWriterTests.cs
Labels: Large, Ready for review

#2079 Support asynchronous invocation of IODataStreamListener.StreamDisposedAsync method from ODataNotificationWriter class
  src/Microsoft.OData.Core/ODataNotificationWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationWriterTests.cs
Labels: Medium, Ready for review

#2091 Setup crank for performance tests
  PerformanceBuild.ps1
  README.md
  benchmarks.yml
  sln/OData.Tests.Performance.sln
  test/PerformanceTests/ComponentTests/Common/Models/ExchangeAttachment.csdl
  test/PerformanceTests/ComponentTests/Microsoft.OData.Performance.ComponentTests.csproj
  test/PerformanceTests/ComponentTests/ODataReader/ODataReaderFeedTests.cs
  test/PerformanceTests/ComponentTests/ODataReader/PayloadGenerator.cs
  test/PerformanceTests/ComponentTests/Scenario/BatchRoundTripPerfTest.cs
  test/PerformanceTests/ComponentTests/Scenario/BinaryDataScaleTests.cs
  test/PerformanceTests/ComponentTests/UriParser/UriParserTests.cs
  test/PerformanceTests/ComponentTests/app.config
  test/PerformanceTests/ComponentTests/packages.config
  test/PerformanceTests/ServiceTests/AssemblyInfo.cs
  test/PerformanceTests/ServiceTests/Common/HttpWebRequestMessage.cs
  test/PerformanceTests/ServiceTests/Common/TestServiceFixture.cs
  test/PerformanceTests/ServiceTests/Microsoft.OData.Performance.ServiceTests.csproj
  test/PerformanceTests/ServiceTests/SimpleQueryTests.cs
  test/PerformanceTests/ServiceTests/UpdateTests.cs
  test/PerformanceTests/ServiceTests/app.config
  test/PerformanceTests/ServiceTests/packages.config
Labels: Extra Large, Ready for review

#2080 Support asynchronous invocation of IODataStreamListener.StreamDisposedAsync method from ODataNotificationStream class
  src/Microsoft.OData.Core/ODataNotificationStream.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationStreamTests.cs
Labels: Medium, Ready for review

#2093 Consistently use CharArrayPool in JsonWriter to cut cost of initializing char arrays
  src/Microsoft.OData.Core/Json/JsonWriter.cs
  src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockCharArrayPool.cs
Labels: Small

#2090 entity tracker equality comparer
  src/Microsoft.OData.Client/EntityTracker.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Tracking/ClientEntityTrackerTests.cs
Labels: Large
