Repository OData/odata.net, pull requests merged in 2021-11, with the labels that each got.

#2217 Implement asynchronous support in JsonReader
  src/Microsoft.OData.Core/ExceptionUtils.cs
  src/Microsoft.OData.Core/Json/JsonReader.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonReaderTests.cs
Labels: Extra Large

#2159 update namespaces to use aliases if aliases for the namespaces are set
  src/Microsoft.OData.Edm/Csdl/CsdlXmlWriter.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelReferenceElementsXmlVisitor.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
Labels: Medium

#2232 Enable property case insensitive reading
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
  src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
  src/Microsoft.OData.Core/ReaderValidationUtils.cs
  src/Microsoft.OData.Core/ReaderValidator.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.cs
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.txt
  src/Microsoft.OData.Edm/Parameterized.Microsoft.OData.Edm.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/PropertyAndValueJsonLightReaderIntegrationTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs
Labels: Medium

#2239 Add direct reference to Microsoft.Bcl.AsyncInterfaces package to fix missing reference issue observed in dependent libraries
  src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
  src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
Labels: Extra Small

#2223 Performance fix for FindAcrossModels
  src/Microsoft.OData.Core/UriParser/Binders/SelectPathSegmentTokenBinder.cs
  src/Microsoft.OData.Core/UriParser/Resolver/UnqualifiedODataUriResolver.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  src/Microsoft.OData.Edm/Schema/EdmModelBase.cs
Labels: Extra Small

#2242 Update version to 7.9.4
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small

#2231 remove single quotes from the type in a cast function
  src/Microsoft.OData.Client/ALinq/ExpressionWriter.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientQueryTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/DollarFilterWithCastTests.cs
  test/FunctionalTests/Service/Microsoft/OData/Service/Parsing/FunctionExpressionBinder.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/TDDUnitTests/Tests/Server/Parsing/NodeToExpressionTranslatorTests.cs
Labels: Small

#2247 Fix memory leak
  src/Microsoft.OData.Client/DataServiceContext.cs
Labels: Ready for review, Extra Small

#2204 Perf: Optimize collections and enumerators
  src/Microsoft.OData.Core/InstanceAnnotationWriteTracker.cs
  src/Microsoft.OData.Core/Json/JsonLightInstanceAnnotationWriter.cs
  src/Microsoft.OData.Core/Json/ODataJsonWriterUtils.cs
  src/Microsoft.OData.Core/ODataAnnotatable.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonLightInstanceAnnotationWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonWriterUtilsAsyncTests.cs
  test/PerformanceTests/ComponentTests/ODataWriter/ODataWriterFeedTests.cs
Labels: Medium

#2248 Implement asynchronous support in JsonReaderExtensions
  src/Microsoft.OData.Core/Json/IJsonReaderAsync.cs
  src/Microsoft.OData.Core/Json/JsonReaderExtensions.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonReaderTests.cs
Labels: Large

#2254 Fix issues with performance tests
  test/PerformanceTests/ComponentTests/ODataReader/ODataReaderFeedTests.cs
  test/PerformanceTests/ComponentTests/ODataWriter/ODataWriterFeedTests.cs
  test/PerformanceTests/SerializationBaselineTests/SerializationBenchmarks.cs
Labels: Extra Small

#2255 Implement asynchronous support in ODataJsonReaderCoreUtils
  src/Microsoft.OData.Core/Json/ODataJsonReaderCoreUtils.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonReaderCoreUtilsTests.cs
Labels: Large

#2250 Support writing nested delta resource sets with non-delta writer.
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightOutputContextApiTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
Labels: Ready for review, Extra Large
