Repository OData/odata.net, pull requests merged in 2022-01, with the labels that each got.

#2277 Fix issue #2276: should use for @type for serializing record in CSDL JSON
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaJsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Serialization/EdmModelCsdlSerializationVisitorTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
Labels: Extra Small

#2215 Performance improvements
  src/Microsoft.OData.Core/Json/JsonValueUtilsAsync.cs
  src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
  src/Microsoft.OData.Core/ODataParameterWriterCore.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
Labels: Small

#2275 Issue #2269: Names starting with underscore must be allowed. Changes …
  src/Microsoft.OData.Edm/EdmUtil.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/EdmUtilTests.cs
Labels: Extra Small

#2191 Compute navigation path should return null if navigation source kind is none in context uri info
  src/Microsoft.OData.Core/ODataContextUrlInfo.cs
Labels: Extra Small

#2279 Default to using entityType for incomplete serializationInfo.
  src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Evaluation/ODataEntryMetadataContextTest.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataReaderDerivedTypeConstraintTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Serialization/EdmModelCsdlSerializationVisitorTests.cs
Labels: Ready for review, Medium

#2288 Cache Parent Scope
  src/Microsoft.OData.Core/ODataReaderCore.cs
Labels: Extra Small

#2281 Onboarding fixes and documentation
  sln/OData.Tests.Performance.md
  sln/OData.Tests.Performance.sln
  sln/OData.Tests.Performance.vsconfig
  sln/odata.md
  sln/odata.vsconfig
  test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
  test/FunctionalTests/Microsoft.Spatial.Tests/Microsoft.Spatial.Tests.csproj
  test/PerformanceTests/ComponentTests/ODataReader/ODataReaderFeedTests.cs
  test/PerformanceTests/ServiceTests/QueryOptionTests.cs
  test/PerformanceTests/ServiceTests/SimpleQueryTests.cs
  test/PerformanceTests/ServiceTests/UpdateTests.cs
Labels: Large

#2297 Onboarding changes for OData.CodeGen.sln and OData.E2E.sln
  Build.props
  sln/OData.CodeGen.md
  sln/OData.CodeGen.vsconfig
  sln/OData.E2E.md
  sln/OData.E2E.vsconfig
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DeleteLinkTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/MaterializeFromXmlUnitTest.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/MediaStreaming.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/ServerDrivenPaging.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/StateManagementTests.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/TDDUnitTests/Microsoft.OData.Service.TDDUnitTests.csproj
  tools/EnableLongPaths.reg
  tools/FxCopRules/DataWebRules.csproj
Labels: Medium
