Repository OData/odata.net, pull requests merged in 2022-02, with the labels that each got.

#2267 Implement asynchronous support in ODataJsonLightDeserializer
  src/Microsoft.OData.Core/Json/IODataJsonOperationsDeserializerContext.cs
  src/Microsoft.OData.Core/Json/ODataJsonReaderCoreUtils.cs
  src/Microsoft.OData.Core/JsonLight/JsonLightConstants.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeserializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceDeserializerTests.cs
Labels: Large

#2299 fix filter using in operator with open types
  src/Microsoft.OData.Core/Uri/ODataUriConversionUtils.cs
  src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/InNode.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
Labels: Extra Small

#2301 Implement asynchronous support in ODataJsonLightEntityReferenceLinkDeserializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightEntityReferenceLinkDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataEntityReferenceLinkTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataEntityReferenceLinksTests.cs
Labels: Extra Large

#2305 Implement asynchronous support in ODataJsonLightErrorDeserializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightErrorDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightErrorDeserializerTests.cs
Labels: Large

#2308 Implement asynchronous support in ODataJsonLightPayloadKindDetectionDeserializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPayloadKindDetectionDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPayloadKindDetectionDeserializerTests.cs
Labels: Large

#2306 Implement asynchronous support ODataJsonLightCollectionDeserializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionDeserializerTests.cs
Labels: Extra Large

#2315 Fix e2e tests build error
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Annotation/InstanceAnnotationDictWeakKeyComparerTests.cs
Labels: Extra Small

#2311 Implement asynchronous support in ODataJsonLightParameterDeserializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterDeserializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs
Labels: Large

#2313 #1208 Support relative context URI starting with "$metadata"
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeserializerTests.cs
Labels: Extra Small

#2325 Add decimal key segment tests
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/PathFunctionalTests.cs
Labels: Extra Small

#2316 Implement asynchronous support in ReorderingJsonReader
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ReorderingJsonReader.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ReorderingJsonReaderTests.cs
Labels: Extra Large

#2322 Implement asynchronous support in ODataJsonLightServiceDocumentDeserializer
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightServiceDocumentDeserializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightServiceDocumentDeserializerTests.cs
Labels: Extra Large

#2324 Implement asynchronous support in ODataNotificationReader
  src/Microsoft.OData.Core/ODataNotificationReader.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationReaderTests.cs
Labels: Medium

#2317 fixed notsupportedexception due to resource table lookup in edmlibtests when run locally
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
Labels: Extra Small

#2327 Implement asynchronous support in ODataJsonLightCollectionReader
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionReader.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionWriterTests.cs
Labels: Medium
