Repository OData/odata.net, pull requests merged in 2022-07, with the labels that each got.

#1925 Support for $apply/groupby
  src/Microsoft.OData.Client/ALinq/ApplyQueryOptionExpression.cs
  src/Microsoft.OData.Client/ALinq/DataServiceQueryProvider.cs
  src/Microsoft.OData.Client/ALinq/GroupByAnalyzer.cs
  src/Microsoft.OData.Client/ALinq/QueryComponents.cs
  src/Microsoft.OData.Client/ALinq/QueryableResourceExpression.cs
  src/Microsoft.OData.Client/ALinq/ResourceBinder.cs
  src/Microsoft.OData.Client/ALinq/UriWriter.cs
  src/Microsoft.OData.Client/GroupByProjectionPlanCompiler.cs
  src/Microsoft.OData.Client/Materialization/MaterializerEntry.cs
  src/Microsoft.OData.Client/Materialization/ODataEntityMaterializer.cs
  src/Microsoft.OData.Client/Materialization/ODataEntityMaterializerInvoker.cs
  src/Microsoft.OData.Client/Microsoft.OData.Client.Common.txt
  src/Microsoft.OData.Client/Microsoft.OData.Client.cs
  src/Microsoft.OData.Client/Microsoft.OData.Client.txt
  src/Microsoft.OData.Client/Parameterized.Microsoft.OData.Client.cs
  src/Microsoft.OData.Client/ProjectionPlanCompiler.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/DollarApplyGroupByTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/DollarApplyTestsBase.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj
Labels: docs-needed, Ready for review, Extra Large

#2461 Add CreateAsynchronousJsonWriter to IStreamBasedJsonWriterFactoryAsync
  src/Microsoft.OData.Core/Json/DefaultStreamBasedJsonWriterFactory.cs
  src/Microsoft.OData.Core/Json/IStreamBasedJsonWriterFactory.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactory.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactoryWrapper.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Small

#2457 Add Writer Comparison Benchmarks
  README.md
  benchmarks.yml
  loadtests.yml
  test/PerformanceTests/SerializationBaselineTests/CharArrayPool.cs
  test/PerformanceTests/SerializationBaselineTests/DataSet.cs
  test/PerformanceTests/SerializationBaselineTests/IExperimentWriter.cs
  test/PerformanceTests/SerializationBaselineTests/JsonExperimentWriter.cs
  test/PerformanceTests/SerializationBaselineTests/Program.cs
  test/PerformanceTests/SerializationBaselineTests/SerializationBaselineTests.csproj
  test/PerformanceTests/SerializationBaselineTests/SerializationBenchmarks.cs
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/ExpectedOutput.txt
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/ExperimentTests.csproj
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/WriterTests.cs
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/Benchmarks.cs
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/JsonWriterBenchmarks.csproj
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/Program.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ContainerBuilder.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/CustomerDataSet.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/DataModel.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/DefaultWriterCollection.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ExperimentsLib.csproj
  test/PerformanceTests/SerializationComparisonsTests/Lib/IPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/JsonSerializerPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/NoopJsonWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/NoopJsonWriterFactory.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterAsyncDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessage.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterAsyncPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/PooledByteArrayBufferWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriterWithArrayPool.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/WriterCollection.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/WriterHelpers.cs
  test/PerformanceTests/SerializationComparisonsTests/README.md
  test/PerformanceTests/SerializationComparisonsTests/SerializationComparisonsTests.sln
  test/PerformanceTests/SerializationComparisonsTests/TestServer/Controllers/CustomersController.cs
  test/PerformanceTests/SerializationComparisonsTests/TestServer/CustomerCollectionOutputFormatter.cs
  test/PerformanceTests/SerializationComparisonsTests/TestServer/Program.cs
  test/PerformanceTests/SerializationComparisonsTests/TestServer/Properties/launchSettings.json
  test/PerformanceTests/SerializationComparisonsTests/TestServer/TestServer.csproj
  test/PerformanceTests/SerializationComparisonsTests/TestServer/appsettings.Development.json
  test/PerformanceTests/SerializationComparisonsTests/TestServer/appsettings.json
Labels: Extra Large
