Repository OData/odata.net, pull requests merged in 2022-04, with the labels that each got.

#2369 added more tests to run with debug configuration and fixed associated…
  azure-pipelines-nightly.yml
  src/Microsoft.OData.Client/BaseSaveResult.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/LinqIntegrationTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/RequestInfoTests.cs
Labels: Medium

#2364 Implement asynchronous support in ODataRawInputContext
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Core/ODataAsynchronousReader.cs
  src/Microsoft.OData.Core/ODataRawInputContext.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataRawInputContextTests.cs
Labels: Large

#2328 Add DuplicatePropertyNameChecker to ObjectPool
  src/Microsoft.OData.Core/IWriterValidator.cs
  src/Microsoft.OData.Core/Json/JsonLightInstanceAnnotationWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightValueSerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
  src/Microsoft.OData.Core/ODataParameterWriterCore.cs
  src/Microsoft.OData.Core/ODataSerializer.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/Uri/ODataUriConversionUtils.cs
  src/Microsoft.OData.Core/WriterValidator.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerTests.cs
Labels: Ready for review, Medium

#2375 consolidating build pipelines and updating nightly pipeline to run de…
  azure-pipelines-nightly.yml
  azure-pipelines-rolling.yml
  buildandtest.yml
  credscan.yml
  nightly.yml
  sln/OData.Pipeline.sln
Labels: Extra Large

#2346 Set default scale to null
  src/Microsoft.OData.Edm/Csdl/CsdlConstants.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/Common/EdmXmlDocumentParser.cs
  src/Microsoft.OData.Edm/Csdl/Parsing/CsdlDocumentParserBase.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaJsonWriter.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaXmlWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/TypePromotionUtilsTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Serialization/EdmModelCsdlSerializationVisitorTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/ConstructibleModelTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/CsdlSerializingTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/ExpressionSerializationTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/ExtensionMethodsTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/OperationModelTests.OperationsWith2ParametersTestRoundtripVerify.approved.txt
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/OperationModelTests.OperationsWithReturnTypeOfPrimitiveDataTypeTestRoundtripVerify.approved.txt
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/ParserTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/RoundTripTests.RoundTripOneComplexWithAllPrimitiveProperty.approved.txt
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/RoundTripTests.RoundTripOneEntityWithAllPrimitiveProperty.approved.txt
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/RoundTripTests.RoundTripTestBuildODataDefaultTestModel.approved.txt
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/SchemaParsingTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/TermAttributeTests.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalUtilities/ODataTestModelBuilder.cs
  test/FunctionalTests/Tests/DataEdmLib/FunctionalUtilities/ValidationTestModelBuilder.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Scenario.Tests/UriParser/Filter/FilterTests.BuiltinDateTimeFunctionFractionalsecondsAndTotaloffsetminutes.approved.txt
  test/FunctionalTests/Tests/DataOData/Tests/OData.Scenario.Tests/UriParser/Filter/FilterTests.BuiltinDateTimeFunctionTotalseconds.approved.txt
  test/FunctionalTests/Tests/DataOData/Tests/OData.Writer.Tests/Writer/WriterMetadataDocumentTests.MetadataDocumentWriterTest.approved.txt
Labels: Ready for review, Medium

#2381 microsoft.odata.test.client.tests has test issues under debug configu…
  buildandtest.yml
  sln/OData.Pipeline.sln
Labels: Extra Small

#2368 adding comments and parameterization to IncrementVersion release script
  tools/IncrementVersion.cmd
  tools/IncrementVersion.ps1
Labels: Small

#2387 revving version number to 7.11.0 and updating PublicAPI.Shipped.txt f…
  src/Microsoft.OData.Core/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicApi/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicApi/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicApi/netstandard2.0/PublicAPI.Shipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small
