Repository OData/odata.net, pull requests merged in 2022-09, with the labels that each got.

#2497 Pass correct output stream to IStreamBasedJsonWriterFactory
  src/Microsoft.OData.Core/Json/DefaultStreamBasedJsonWriterFactory.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/DefaultStreamBasedJsonWriterFactoryAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/DefaultStreamBasedJsonWriterFactoryTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchWriterTests.cs
Labels: Medium

#2506 Replace ConditionalWeakTable with simpler non-static Dictionary-based cache
  src/Microsoft.OData.Client/AtomMaterializerLog.cs
  src/Microsoft.OData.Client/BaseAsyncResult.cs
  src/Microsoft.OData.Client/BatchSaveResult.cs
  src/Microsoft.OData.Client/DataServiceRequest.cs
  src/Microsoft.OData.Client/Materialization/CollectionValueMaterializationPolicy.cs
  src/Microsoft.OData.Client/Materialization/EntityTrackingAdapter.cs
  src/Microsoft.OData.Client/Materialization/EntryValueMaterializationPolicy.cs
  src/Microsoft.OData.Client/Materialization/EnumValueMaterializationPolicy.cs
  src/Microsoft.OData.Client/Materialization/FeedAndEntryMaterializerAdapter.cs
  src/Microsoft.OData.Client/Materialization/IODataMaterializerContext.cs
  src/Microsoft.OData.Client/Materialization/MaterializerCache.cs
  src/Microsoft.OData.Client/Materialization/MaterializerContextExtensions.cs
  src/Microsoft.OData.Client/Materialization/MaterializerEntry.cs
  src/Microsoft.OData.Client/Materialization/MaterializerFeed.cs
  src/Microsoft.OData.Client/Materialization/MaterializerNavigationLink.cs
  src/Microsoft.OData.Client/Materialization/ODataEntityMaterializer.cs
  src/Microsoft.OData.Client/Materialization/ODataEntityMaterializerInvoker.cs
  src/Microsoft.OData.Client/Materialization/ODataItemExtensions.cs
  src/Microsoft.OData.Client/Materialization/ODataMaterializer.cs
  src/Microsoft.OData.Client/Materialization/ODataMaterializerContext.cs
  src/Microsoft.OData.Client/Materialization/ODataMessageReaderMaterializer.cs
  src/Microsoft.OData.Client/Materialization/ODataReaderEntityMaterializer.cs
  src/Microsoft.OData.Client/Materialization/PrimitiveValueMaterializationPolicy.cs
  src/Microsoft.OData.Client/Materialization/StructuralValueMaterializationPolicy.cs
  src/Microsoft.OData.Client/MaterializeFromAtom.cs
  src/Microsoft.OData.Client/ODataAnnotatableExtensions.cs
  src/Microsoft.OData.Client/ProjectionPlanCompiler.cs
  src/Microsoft.OData.Client/QueryResult.cs
  src/Microsoft.OData.Client/SaveResult.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceRequestTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/CollectionValueMaterializationPolicyTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/EntryMaterializationPolicyForComplexResourceTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/EntryValueMaterializationPolicyUnitTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/FeedAndEntryMaterializerAdapterUnitTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/MaterializerEntryTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/ODataEntityMaterializerUnitTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/ODataEntriesEntityMaterializerUnitTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/PrimitiveValueMaterializationPolicyTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/TestMaterializerContext.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/T4/ODataT4CamelCaseTests.cs
Labels: Extra Large

#2509 Update version to 7.12.3
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small

#2496 Fix #1529 by first checking that a property was found
  src/Microsoft.OData.Core/UriParser/Binders/EndPathBinder.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/EndPathBinderTests.cs
Labels: Extra Small

#2481 Performance refactor - elide async and await
  src/Microsoft.OData.Core/Batch/ODataBatchOperationMessage.cs
  src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
  src/Microsoft.OData.Core/Json/JsonLightInstanceAnnotationWriter.cs
  src/Microsoft.OData.Core/Json/JsonReader.cs
  src/Microsoft.OData.Core/Json/JsonReaderExtensions.cs
  src/Microsoft.OData.Core/Json/JsonValueUtilsAsync.cs
  src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
  src/Microsoft.OData.Core/Json/JsonWriterAsyncExtensions.cs
  src/Microsoft.OData.Core/Json/ODataJsonReaderCoreUtils.cs
  src/Microsoft.OData.Core/Json/ODataJsonWriterUtils.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionSerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightEntityReferenceLinkSerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceSerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightSerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightServiceDocumentSerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightValueSerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
  src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchOutputContext.cs
  src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs
  src/Microsoft.OData.Core/ODataAsynchronousWriter.cs
  src/Microsoft.OData.Core/ODataBinaryStreamReader.cs
  src/Microsoft.OData.Core/ODataBinaryStreamWriter.cs
  src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
  src/Microsoft.OData.Core/ODataMessage.cs
  src/Microsoft.OData.Core/ODataMessageReader.cs
  src/Microsoft.OData.Core/ODataMessageWriter.cs
  src/Microsoft.OData.Core/ODataMetadataFormat.cs
  src/Microsoft.OData.Core/ODataParameterReaderCoreAsync.cs
  src/Microsoft.OData.Core/ODataParameterWriterCore.cs
  src/Microsoft.OData.Core/ODataReaderCore.cs
  src/Microsoft.OData.Core/ODataUtils.cs
  src/Microsoft.OData.Core/ODataWriter.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/RawValueWriter.cs
  src/Microsoft.OData.Core/TaskUtils.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Large

#2493 fix the ordering of an assertion
  test/FunctionalTests/Microsoft.OData.Core.Tests/AssertExtensions.cs
Labels: Extra Small

#2500 ODataUriSlim struct
  src/Microsoft.OData.Core/Evaluation/ODataConventionalIdMetadataBuilder.cs
  src/Microsoft.OData.Core/Evaluation/ODataMetadataContext.cs
  src/Microsoft.OData.Core/JsonLight/JsonFullMetadataLevel.cs
  src/Microsoft.OData.Core/JsonLight/JsonLightMetadataLevel.cs
  src/Microsoft.OData.Core/JsonLight/JsonMinimalMetadataLevel.cs
  src/Microsoft.OData.Core/JsonLight/JsonNoMetadataLevel.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
  src/Microsoft.OData.Core/ODataContextUrlInfo.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/Uri/ODataUriSlim.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Evaluation/ODataMissingOperationGeneratorTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriterCoreTests.cs
Labels: Large
