Repository OData/odata.net, pull requests merged in 2022-12, with the labels that each got.

#2566 odata.id annotation property should be written for transient complex resource
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceSerializer.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
Labels: Small

#2558 Validate that a recursive complex-typed property must be nullable
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.cs
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.txt
  src/Microsoft.OData.Edm/Parameterized.Microsoft.OData.Edm.cs
  src/Microsoft.OData.Edm/Validation/EdmErrorCode.cs
  src/Microsoft.OData.Edm/Validation/ValidationRules.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRuleSetTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRulesTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Medium

#2552 issue #2098: fix the issue ODataException: To compute an entity's metadata, its key and concurrency-token property values must be provided
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs
Labels: Large

#2575 Fix PublicAPI build checks
  src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: Medium

#2527 Fix bugs causing separator to be omitted after ODataUtf8JsonWriter.WriteRawValue
  loadtests.yml
  src/Microsoft.OData.Core/Json/BitStack.cs
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/BitStackTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/ExpectedOutput.txt
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/WriterTests.cs
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/Benchmarks.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/CustomerDataSet.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/DataModel.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/IPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/JsonSerializerPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterAsyncDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterAsyncPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriterWithArrayPool.cs
  test/PerformanceTests/SerializationComparisonsTests/README.md
  test/PerformanceTests/SerializationComparisonsTests/TestServer/CustomerCollectionOutputFormatter.cs
Labels: Extra Large

#2569 Fix performance regression in DataServiceContext DefaultResolveType method
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/CamelCasedTypeMaterializationTests.cs
Labels: Medium

#2582 revving version number to 7.13.0 and updating PublicAPI.Shipped.txt f…
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.Spatial/PublicAPI.Shipped.txt
  src/Microsoft.Spatial/PublicAPI.Unshipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Extra Large

#2572 fix: ExpressionWriter only prepend slash to method when we have a parent
  src/Microsoft.OData.Client/ALinq/ExpressionWriter.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceQueryProviderTests.cs
Labels: Extra Small

#2573 Ported DataServiceContext.AutoNullPropagation from V3 ODL
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/Materialization/IODataMaterializerContext.cs
  src/Microsoft.OData.Client/Materialization/MaterializerEntry.cs
  src/Microsoft.OData.Client/Materialization/ODataEntityMaterializer.cs
  src/Microsoft.OData.Client/Materialization/ODataEntityMaterializerInvoker.cs
  src/Microsoft.OData.Client/Materialization/ODataMaterializerContext.cs
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/ResponseInfo.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/TestMaterializerContext.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Small
