Repository OData/odata.net, pull requests merged in 2022-08, with the labels that each got.

#2466 Implement ODataUtf8JsonWriter async API
  benchmarks.yml
  src/Microsoft.OData.Core/Json/DefaultStreamBasedJsonWriterFactory.cs
  src/Microsoft.OData.Core/Json/IStreamBasedJsonWriterFactory.cs
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/ODataMessageWriter.cs
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/AssertExtensions.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/DefaultStreamBasedJsonWriterFactoryAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockAsyncOnlyJsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockJsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockJsonWriterFactoryAsync.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactory.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactoryWrapper.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockSyncOnlyJsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/SingletonBatchRoundtripJsonLightTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonReaderWriterInjectionTests.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/DefaultWriterCollection.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriterWithArrayPool.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/WriterHelpers.cs
  test/PerformanceTests/SerializationComparisonsTests/README.md
Labels: Extra Large

#2157 method to get all navigation property bindings
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Semantics/CsdlSemanticsEntityContainerTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Small

#2470 Issue2467: Support Core.AlternateKeys
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyConstants.cs
  src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyModel.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Medium

#2476 Update version to 7.12.2
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small

#2492 Ensure service host is closed after each test
  test/EndToEndTests/Tests/Client/Build.Desktop/AnnotationTests/InstanceAnnotationTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/AsyncRequestTests/AsyncRequestTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/BatchRequestTests/BatchRequestWithRelativeUriTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientDeleteTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientEntityDescripterTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/CollectionTests/CollectionNullableFacetTest.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ComplexTypeTests/ComplexTypeTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ContainmentTest/ContainmentTest.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/DeltaTests/DeltaTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/DisableAtomTests/DisableAtomTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/EdmDateAndTimeOfDay/DateAndTimeOfDayCRUDTestings.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/EnumerationTypeTests/EnumerationTypeQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/EnumerationTypeTests/EnumerationTypeUpdateTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ModelReferenceTests/ModelReferenceCUDTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ModelReferenceTests/ModelReferenceClientTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ModelReferenceTests/ModelReferenceQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ODataSimplifiedServiceTests/ODataSimplifiedServiceTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTests/AbstractEntityTypeTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTests/IDReadLinkEditLinkTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTests/ODataWCFServiceQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTests/ODataWCFServiceUpdateTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTestsBase.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/OperationTests/OperationClientTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/OperationTests/OperationT4Tests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/PayloadValueConverterTests/PayloadValueConverterTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/PluggableFormatServiceTests/PluggableFormatServiceTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/PrimitiveTypesTests/DurationTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/PropertyTrackingTests/PostPropertyTrackingTest.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/QueryOptionTests/EntityReferenceLinkTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/QueryOptionTests/ExpandQueryOptionTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/QueryOptionTests/FilterQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/QueryOptionTests/OrderbyQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/QueryOptionTests/QueryOptionOnCollectionTypePropertyTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/QueryOptionTests/SearchQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/SingletonTests/SingletonClientTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/SingletonTests/SingletonQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/SingletonTests/SingletonUpdateTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/TripPinServiceTests/TripPinFilterTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/TripPinServiceTests/TripPinServiceTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/TypeDefinitionTests/TypeDefinitionTests.cs
Labels: Medium

#2487 Fix bug in LoadProperty for complex and complex collection
  src/Microsoft.OData.Client/Materialization/ODataLoadNavigationPropertyMaterializer.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/LoadPropertyTests.cs
Labels: Large

#2495 Make ODataPath.Segments property read-only
  src/Microsoft.OData.Core/BindingPathHelper.cs
  src/Microsoft.OData.Core/EdmExtensionMethods.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs
Labels: Extra Small

#2489 Create optimized ODataPath cloning constructor
  src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathTests.cs
Labels: Extra Small
