Repository OData/odata.net, pull requests merged in 2022-11, with the labels that each got.

#2521 shouldn't require id to write a deleted resource
  src/Microsoft.OData.Core/ODataWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
Labels: Extra Small

#2551 Update onboarding documentation to note that long repository root paths can cause build failures
  sln/OData.E2E.md
  sln/odata.md
Labels: Extra Small

#2547 added logic to treat a dynamic property that contains a json array as…
  src/Microsoft.OData.Client/ODataMessageReadingHelper.cs
  src/Microsoft.OData.Core/Json/JsonReaderExtensions.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
  src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Data/UntypedCollection/DirectoryInternalSchema_Version27.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Data/UntypedCollection/failedresponse.json
  test/FunctionalTests/Microsoft.OData.Client.Tests/Data/UntypedCollection/version27.xml
  test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceContextHttpClientHandlerProviderTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Client.Tests/Tracking/DataServiceContextNoTrackingStreamsTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerUndeclaredAnnotationTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerUndeclaredTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Large

#2504 Support NavigationPropertyBinding paths ending in cast segments
  sln/OData.sln
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsNavigationSource.cs
  src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaXmlWriter.cs
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
  src/Microsoft.OData.Edm/Schema/EdmNavigationSource.cs
  src/Microsoft.OData.Edm/Validation/ValidationRules.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderJsonTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Semantics/CsdlSemanticsEntitySetTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
Labels: Extra Large

#2559 Add test for throwing exception for multiple unnamed keys
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/PathFunctionalTests.cs
Labels: Extra Small
