Repository OData/odata.net, pull requests merged in 2022-03, with the labels that each got.

#2300 Fix cast in expand
  src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
  src/Microsoft.OData.Core/UriParser/ODataPathInfo.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
Labels: Ready for review, Medium

#2336 addressed local test failures from `Microsoft.Data.ServerUnitTests1.UnitTests`
  azure-pipelines-nightly.yml
  test/FunctionalTests/Service/Microsoft/OData/Service/Providers/MetadataProviderEdmEntityContainer.cs
  test/FunctionalTests/Service/Microsoft/OData/Service/Providers/MetadataProviderEdmEntitySet.cs
  test/FunctionalTests/Service/Microsoft/OData/Service/Providers/MetadataProviderEdmModel.cs
Labels: Small

#2347 adding more tests to run with debug configuration during nightly builds
  azure-pipelines-nightly.yml
  test/FunctionalTests/Tests/DataServices/UnitTests/RegressionUnitTests/Microsoft.Data.Web.RegressionUnitTests.csproj
Labels: Extra Small

#2341 Validate key not defined multiple times in type hierarchy
  src/Microsoft.OData.Edm/PublicApi/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicApi/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/Validation/ValidationRuleSet.cs
  src/Microsoft.OData.Edm/Validation/ValidationRules.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRuleSetTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRulesTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Medium

#2335 Implement asynchronous support in ODataJsonLightReader
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/ODataReaderCore.cs
  src/Microsoft.OData.Core/ODataReaderCoreAsync.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
Labels: Extra Large

#2349 added script to increment version number and update PublicAPI.Shipped…
  tools/IncrementVersion.cmd
  tools/IncrementVersion.ps1
Labels: Extra Small

#2345 added publicapi tests to e2e solution and fixed test helper…
  azure-pipelines-nightly.yml
  azure-pipelines-rolling.yml
  sln/OData.E2E.sln
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
  test/PublicApiTests/PublicApiHelper.cs
Labels: Small

#2350 added more tests to debug configuration in nightly build and fixed te…
  azure-pipelines-nightly.yml
  test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Microsoft.Data.Web.UnitTests.csproj
  test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/RequestQueryParserTest.cs
Labels: Extra Small

#2355 added Microsoft.Data.WebClient.UnitTests to build pipeline and fixed …
  azure-pipelines-nightly.yml
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/LinqAnyAllTests.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/MaterializationTest.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/Microsoft.Data.WebClient.UnitTests.vbproj
Labels: Extra Small

#2351 Implement asynchronous support in ODataJsonLightDeltaReader
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeltaReader.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightReaderTests.cs
Labels: Extra Large

#2362 Temporarily moving build pipelines from `windows-latest` to `windows-2019`
  azure-pipelines-nightly.yml
  azure-pipelines-rolling.yml
Labels: Extra Small

#2353 Implement asynchronous support in ODataJsonLightParameterReader
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterReader.cs
  src/Microsoft.OData.Core/ODataParameterReader.cs
  src/Microsoft.OData.Core/ODataParameterReaderCore.cs
  src/Microsoft.OData.Core/ODataParameterReaderCoreAsync.cs
  src/Microsoft.OData.Core/PublicAPI.Unshipped.txt
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterReaderTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Large

#2366 ODataJsonLightCollectionReader improvements to reduce delegate allocations
  src/Microsoft.OData.Core/ODataCollectionReaderCore.cs
Labels: Extra Small

#2367 Fix unnecessary delegate allocations across OData writers
  src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
  src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
  src/Microsoft.OData.Core/ODataParameterWriterCore.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Small

#2360 added Microsoft.Data.WebClientCharp.UnitTests to work run under release …
  azure-pipelines-nightly.yml
  src/Microsoft.OData.Client/Microsoft.OData.Client.txt
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ClientCSharpRegressionTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/LinqAnyAllTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/LinqTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/Microsoft.Data.WebClientCSharp.UnitTests.csproj
Labels: Extra Small

#2359 Implement asynchronous support in ODataJsonLightBatchReader
  src/Microsoft.OData.Core/Batch/ODataBatchReader.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchBodyContentReaderStream.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchPayloadItemPropertiesCache.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchReader.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/PublicAPI.Unshipped.txt
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchReaderTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Large
