Repository OData/odata.net, pull requests merged in 2023-02, with the labels that each got.

#2612 Update Validation Vocabulary
  src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml
  src/Microsoft.OData.Edm/Vocabularies/VocabularyModelProvider.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/ValidationVocabularyTests.cs
Labels: Large

#2610 Create cache to speed up case-insensitive look up of schema elements
  src/Microsoft.OData.Core/UriParser/Resolver/NormalizedSchemaElementsCache.cs
  src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/NormalizedSchemaElementsCacheTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ODataUriResolverTests.cs
  test/PerformanceTests/ComponentTests/Common/Models/TripPin.csdl
  test/PerformanceTests/ComponentTests/Common/TestUtils.cs
  test/PerformanceTests/ComponentTests/Microsoft.OData.Performance.ComponentTests.csproj
  test/PerformanceTests/ComponentTests/UriParser/UriParserTests.cs
Labels: Extra Large

#2600 Flush out release process documentation
  docs/release.md
Labels: Small

#2614 Add vocabulary terms to Require Explicit Binding
  src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
Labels: Extra Small

#2616 Fix broken link
  README.md
Labels: Extra Small

#2603 fixes #2598, Composite key entities PUT,PATCH URIs generated by OData Client do not follow key order
  src/Microsoft.OData.Client/ALinq/QueryableResourceExpression.cs
  src/Microsoft.OData.Client/ALinq/ResourceBinder.cs
  src/Microsoft.OData.Client/ClientEdmModel.cs
  src/Microsoft.OData.Client/Metadata/ODataTypeInfo.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ClientEdmModelTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/LinqIntegrationTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/TemplatingIntegrationTests.cs
Labels: Medium

#2615 Increment version number and update public api txt files
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small

#2619 Add support for writing JsonElement values in ODataWriter
  benchmarks.yml
  src/Microsoft.OData.Core/Json/IJsonWriter.cs
  src/Microsoft.OData.Core/Json/IJsonWriterAsync.cs
  src/Microsoft.OData.Core/Json/JsonWriter.cs
  src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightValueSerializer.cs
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/Value/ODataJsonElementValue.cs
  src/Microsoft.OData.Core/Value/ODataValueUtils.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockAsyncOnlyJsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockJsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockSyncOnlyJsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataValueUtilsTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonReaderWriterInjectionTests.cs
  test/PerformanceTests/ComponentTests/Common/ODataMessageHelper.cs
  test/PerformanceTests/ComponentTests/ODataWriter/JsonElementPropertyTests.cs
  test/PerformanceTests/ComponentTests/ODataWriter/ODataWriterFeedTests.cs
  test/PerformanceTests/ComponentTests/ODataWriter/WriteFeedPropertyTypeTests.cs
Labels: Extra Large

#2624 Fix ArgumentException regression in ProjectPlanCompiler
  src/Microsoft.OData.Client/ProjectionPlanCompiler.cs
  test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
Labels: Extra Small

#2618 support reading relative context urls with bulk updates
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightContextUriParser.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/ODataConstants.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightContextUriParserTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/ContextUriParserJsonLightTests.cs
Labels: Small

#2623 Cache container elements in ODataUriResolver model elements cache
  src/Microsoft.OData.Core/UriParser/Resolver/NormalizedModelElementsCache.cs
  src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/NormalizedModelElementsCacheTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ODataUriResolverTests.cs
Labels: Large
