Repository OData/odata.net, pull requests merged in 2023-09, with the labels that each got.

#2729 Add support for NaN and infinity to ODataUtf8JsonWriter
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
Labels: Small

#2716 Feature/deep insert async
  src/Microsoft.OData.Client/BaseSaveResult.cs
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/DeepInsertSaveResult.cs
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/Util.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DeepInsertE2ETests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Large

#2731 Update version to 7.18.0
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small

#2741 added an endpoint to receive csdl uploads
  Portal/Controllers/CsdlController.cs
  Portal/Program.cs
Labels: Extra Small

#2742 updated csdl uploads to actually use backing storage
  Portal/Controllers/CsdlController.cs
  Portal/appsettings.Development.json
  README.md
Labels: Small

#2743 Hackathon/peachy/sakethkollu/implement go button
  .gitignore
  App.sln
  ODataPlayground/Makefile
  ODataPlayground/ODataPlayground.Frontend/src/pages/index.tsx
  ODataPlayground/ODataPlayground.Server/ClientApp/404.html
  ODataPlayground/ODataPlayground.Server/ClientApp/SwaggerUI.html
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/PqaRTKVLOZ01OxHD21p5Y/_buildManifest.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/TG7GYzCjIaPLj0Z-DSvcM/_buildManifest.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/TG7GYzCjIaPLj0Z-DSvcM/_ssgManifest.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/chunks/268-d2dca70b32f6763c.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/chunks/87-83f15c8493be8ed3.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/chunks/pages/index-08c01ba359c67d9f.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/chunks/pages/index-b6a455c9bf0b294a.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/chunks/pages/index-f23dea6b89b6ac08.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/qyqpc_UCOVGUT5Wx2CQ5r/_buildManifest.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/qyqpc_UCOVGUT5Wx2CQ5r/_ssgManifest.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/xyWSjMjDrbgJUtIZjqSXX/_buildManifest.js
  ODataPlayground/ODataPlayground.Server/ClientApp/_next/static/xyWSjMjDrbgJUtIZjqSXX/_ssgManifest.js
  ODataPlayground/ODataPlayground.Server/ClientApp/index.html
  ODataPlayground/ODataPlayground.Server/Controllers/CsdlController.cs
  ODataPlayground/ODataPlayground.Server/ODataPlayground.Server.csproj
  ODataPlayground/ODataPlayground.Server/appsettings.Development.json
Labels: Medium
