Repository OData/odata.net, pull requests merged in 2023-11, with the labels that each got.

#2788 Upgrade Microsoft.Bcl.AsyncInterfaces dependency to 7.0.0
  src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
  src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
  src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
  src/Microsoft.OData.Core/GlobalSuppressions.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
  src/Microsoft.Spatial/Microsoft.Spatial.csproj
  test/Common/Microsoft.Test.OData.DependencyInjection/Microsoft.Test.OData.DependencyInjection.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
  test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj
Labels: Extra Small

#2779 Fix issue in parsing OData core vocabulary
  src/Microsoft.OData.Edm/Vocabularies/AlternateKeysVocabularies.xml
  src/Microsoft.OData.Edm/Vocabularies/AuthorizationVocabularies.xml
  src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularies.xml
  src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml
  src/Microsoft.OData.Edm/Vocabularies/MeasuresVocabularies.xml
  src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/AlternateKeysVocabularyTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/AuthorizationVocabularyTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CapabilitiesVocabularyTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/ValidationVocabularyTests.cs
Labels: Extra Large

#2793 Upgrade Microsoft.Bcl.AsyncInterfaces dependency to 8.0.0
  src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
  src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
  test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj
Labels: Extra Small

#2681 updated odata.context computation to remove trailing cast segments th…
  src/Microsoft.OData.Core/ODataContextUrlInfo.cs
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/System/Collections/Generic/ReadOnlyListExtensions.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/GenerateContextUrlFromSlimUriWithDerivedTypeCastAndKeySegment.xml
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/WriteContextWithDerivedTypeCastAndKeySegmentAsync.xml
  test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathExtensionsTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/System/Collections/Generic/ReadOnlyListExtensionsTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Large

#2755 Use same format as JsonWriter when serializing DateTimeOffset with ODataUtf8JsonWriter
  src/Microsoft.OData.Core/Json/JsonValueUtils.cs
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
Labels: Extra Small

#2799 Support deserialization of OData error with multiple items in the error details collection
  src/Microsoft.OData.Core/Json/BufferingJsonReader.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/BufferingJsonReaderTests.cs
Labels: Medium

#2792 Reduce buffer allocations
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  src/Microsoft.OData.Core/Json/PooledByteBufferWriter.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
  src/Microsoft.OData.Core/ODataMetadataOutputContext.cs
  src/Microsoft.OData.Core/ODataRawOutputContext.cs
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/PooledByteBufferWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterSettingsTests.cs
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/Benchmarks.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterAsyncPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterPayloadWriter.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Large

#2809 Bump version to 7.19.0
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Small

#2808 Slight performance improvement for `IEdmNavigationSource.EntityType()`
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsEntitySet.cs
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsSingleton.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
Labels: Extra Small
