Repository OData/odata.net, pull requests merged in 2023-05, with the labels that each got.

#2664 fixes #2659: Support declared Edm.Untyped property serialization using ODataPrimitiveValue, etc
  src/Microsoft.OData.Core/TypeNameOracle.cs
  src/Microsoft.OData.Core/ValidationUtils.cs
  src/Microsoft.OData.Core/WriterValidator.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedSerializerUndecalredTests.cs
Labels: Medium

#2666 fixes #2661. Write the nested resource within nested collection in collection
  src/Microsoft.OData.Core/ODataWriterCore.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedSerializerUndecalredTests.cs
Labels: Extra Small

#2667 Update the release version to 7.15.16
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small

#2670 fix nightly hang issue
  src/Microsoft.OData.Client/Materialization/MaterializerCache.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/BulkUpdateE2ETests.cs
Labels: Extra Small

#2671 fix nuget installer issue
  buildandtest.yml
Labels: Extra Small

#2653 Feature/deep insert request
  src/Microsoft.OData.Client/BulkUpdateSaveResult.cs
  src/Microsoft.OData.Client/ClientEdmModel.cs
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/DeepInsertSaveResult.cs
  src/Microsoft.OData.Client/Microsoft.OData.Client.Common.txt
  src/Microsoft.OData.Client/Microsoft.OData.Client.cs
  src/Microsoft.OData.Client/Microsoft.OData.Client.txt
  src/Microsoft.OData.Client/Parameterized.Microsoft.OData.Client.cs
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/SaveChangesOptions.cs
  src/Microsoft.OData.Client/Serialization/Serializer.cs
  src/Microsoft.OData.Client/Util.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceContextTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DeepInsertSaveResultTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Large
