Repository OData/odata.net, pull requests merged in 2023-03, with the labels that each got.

#2629 Update version to 7.15.0
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small

#2561 bulk update request
  src/Microsoft.OData.Client/BaseSaveResult.cs
  src/Microsoft.OData.Client/BulkUpdateGraph.cs
  src/Microsoft.OData.Client/BulkUpdateSaveResult.cs
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/ODataMessageWritingHelper.cs
  src/Microsoft.OData.Client/ODataRequestMessageWrapper.cs
  src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/SaveChangesOptions.cs
  src/Microsoft.OData.Client/SendingRequest2EventArgs.cs
  src/Microsoft.OData.Client/Serialization/ODataWriterWrapper.cs
  src/Microsoft.OData.Client/Serialization/Serializer.cs
  src/Microsoft.OData.Client/Util.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/BulkUpdateSaveResultTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Large

#2635 Fix function path validation
  src/Microsoft.OData.Core/UrlValidation/ValidationEngine/PathSegmentValidator.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
Labels: Extra Small

#2641 Apply tracing to OData write APIs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/TelemetryContants.cs
  src/Microsoft.OData.Core/TelemetryHelper.cs
Labels: Large

#2639 Add telemetry to validations
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Core/Telemetry/TelemetryProvider.cs
  src/Microsoft.OData.Core/WriterValidationUtils.cs
Labels: Small

#2645 Consolidate telemetry efforts and add to pipeline
  azure-pipelines-rolling.yml
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/Telemetry.cs
  src/Microsoft.OData.Core/Telemetry/TelemetryConstants.cs
  src/Microsoft.OData.Core/Telemetry/TelemetryHelper.cs
  src/Microsoft.OData.Core/Telemetry/TelemetryProvider.cs
  src/Microsoft.OData.Core/WriterValidationUtils.cs
Labels: Medium
