Repository OData/odata.net, pull requests merged in 2023-12, with the labels that each got.

#2811 Add index-based access to ODataPath
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Small

#2786 fixes #2785: support property instance annotation without property value
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReaderNestedPropertyInfo.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
  src/Microsoft.OData.Core/PropertyAndAnnotationCollector.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceDeserializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Streaming/ODataJsonLightStreamReadingTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Streaming/ODataJsonLightStreamWritingTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/StreamReferenceValueReaderJsonLightTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/Reader/AssociationLinkReaderTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/Reader/PropertyReaderTests.cs
Labels: Large

#2769 Feature IEdmTargetPath to support path to a model element
  src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs
  src/Microsoft.OData.Edm/Csdl/SerializationExtensionMethods.cs
  src/Microsoft.OData.Edm/EdmUtil.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  src/Microsoft.OData.Edm/ExtensionMethods/TargetPathHelper.cs
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.cs
  src/Microsoft.OData.Edm/Microsoft.OData.Edm.txt
  src/Microsoft.OData.Edm/Parameterized.Microsoft.OData.Edm.cs
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/Schema/EdmTargetPath.cs
  src/Microsoft.OData.Edm/Schema/Interfaces/IEdmTargetPath.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.TargetPath.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.TargetPath.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/EdmUtilTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/TargetHelperTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Schema/EdmTargetPathTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Large

#2810 Micro-optimization for `IsPrimitiveType`
  src/Microsoft.OData.Core/Metadata/EdmLibraryExtensions.cs
Labels: Extra Small

#2826 Increment build version to 7.20.0
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Small
