Repository OData/odata.net, pull requests merged in 2023-08, with the labels that each got.

#2711 Support $filter=dynamicProperty in ('')
  src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
Labels: Extra Small

#2707 Remove sync I/O from JsonValueUtils async write methods
  src/Microsoft.OData.Core/Json/JsonValueUtils.cs
  src/Microsoft.OData.Core/Json/JsonValueUtilsAsync.cs
  src/Microsoft.OData.Core/Json/NonIndentedTextWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonValueUtilsAsyncTests.cs
Labels: Medium

#2676 added a custom trace listener to test projects that handles Debug.A…
  test/App.Debug.config
  test/App.config
  test/Build.Debug.props
  test/Build.props
  test/CommonAssemblies/Transform/CollectFiles/Microsoft.Web.Publishing.AllFilesInProjectFolder.targets
  test/CommonAssemblies/Transform/CollectFiles/Microsoft.Web.Publishing.AllFilesInTheProject.targets
  test/CommonAssemblies/Transform/CollectFiles/Microsoft.Web.Publishing.OnlyFilesToRunTheApp.targets
  test/CommonAssemblies/Transform/Deploy/Microsoft.Web.Publishing.Deploy.FPSE.targets
  test/CommonAssemblies/Transform/Deploy/Microsoft.Web.Publishing.Deploy.FTP.targets
  test/CommonAssemblies/Transform/Deploy/Microsoft.Web.Publishing.Deploy.FileSystem.targets
  test/CommonAssemblies/Transform/Deploy/Microsoft.Web.Publishing.Deploy.MsDeploy.targets
  test/CommonAssemblies/Transform/Deploy/Microsoft.Web.Publishing.Deploy.Package.targets
  test/CommonAssemblies/Transform/Deploy/Microsoft.Web.Publishing.MsDeploy.Common.targets
  test/CommonAssemblies/Transform/Microsoft.Web.Publishing.Tasks.dll
  test/CommonAssemblies/Transform/Microsoft.Web.Publishing.targets
  test/CommonAssemblies/Transform/Microsoft.Web.Publishing/ImportAfter/Microsoft.Web.AzureAD.Publishing.targets
  test/CommonAssemblies/Transform/Microsoft.Web.XmlTransform.dll
  test/CommonAssemblies/Transform/Microsoft.WebSite.Publishing.targets
  test/CommonAssemblies/Transform/Transform/Microsoft.Web.Publishing.AspNetCompileMerge.targets
  test/EndToEndTests/Services/Astoria/Microsoft.Test.OData.Services.Astoria.xml
  test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
  test/FunctionalTests/Microsoft.OData.TestCommon/DebugAssertTraceListener.cs
  test/FunctionalTests/Microsoft.OData.TestCommon/Fake.cs
  test/FunctionalTests/Microsoft.OData.TestCommon/Fake.vb
  test/FunctionalTests/Microsoft.OData.TestCommon/Microsoft.OData.TestCommon.csproj
  test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj
Labels: Extra Large

#2677 update CI pipeline to run both Debug and Release configurations
  azure-pipelines-rolling.yml
Labels: Small

#2709 Rename AAD to Entra ID
  docs/release.md
Labels: Extra Small
