Repository OData/odata.net, pull requests merged in 2024-04, with the labels that each got.

#2915 Remove Credentials and ReadWriteTimeout deprecated overrides
  test/EndToEndTests/Tests/Client/Build.Desktop/TransportLayerTests/HttpClientRequestMessage.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/TransportLayerTests/RequestMessageArgsTests.cs
Labels: Extra Small

#2914 #2913 switch to license expression
  src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec
  src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec
  src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
  src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
  src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec
  src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec
  src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec
  src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
Labels: Extra Small

#2923 Fix DeepInsert issue with matching RelatedDescriptors to NestedItems
  src/Microsoft.OData.Client/DeepInsertSaveResult.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DeepInsertE2ETests.cs
Labels: Large

#2924 Fix E2E tests failure
  test/CommonAssemblies/Microsoft.VisualStudio.QualityTools.UnitTestFramework.10.0.0/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  test/CommonAssemblies/Microsoft.VisualStudio.QualityTools.UnitTestFramework.15.0.0/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  test/CommonAssemblies/Microsoft.VisualStudio.QualityTools.UnitTestFramework.17.0.0/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  test/EndToEndTests/Services/ServiceWrapperApp/ServiceWrapperApp.csproj
  test/EndToEndTests/Tests/Client/Build.Desktop/Microsoft.Test.OData.Tests.Client.csproj
Labels: Extra Small

#2925 Throw an ODataException with helpful message when type name in context URL is not qualified
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/TypeUtils.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/TypeUtilsTests.cs
Labels: Extra Small

#2880 Implement streaming API in ODataUtf8JsonWriter
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.Stream.cs
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.TextWriter.cs
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonTextWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterStreamTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
Labels: Extra Large

#2922 Fix EdmTargetPath property collections
  src/Microsoft.OData.Edm/ExtensionMethods/TargetPathHelper.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.TargetPath.cs
Labels: Extra Small

#2928 Fix CA1002 violiation on ODataUrlValidationContext class
  src/Microsoft.OData.Core/GlobalSuppressions.cs
  src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/UrlValidation/ODataUrlValidationContext.cs
  src/Microsoft.OData.Core/UrlValidation/Rules/DeprecationRules.cs
  src/Microsoft.OData.Core/UrlValidation/Rules/RequireSelectRules.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UrlValidation/ODataUrlValidatorTests.cs
Labels: Extra Small

#2929 Fix ODL-8 E2E solution build failures
  test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/HttpClientRequestMessageTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/MediaStreaming.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/StateChange.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/UpdateTests.vb
Labels: Small

#2930 Update version to 7.21.0
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  tools/CustomMSBuild/Versioning.props
Labels: Extra Small
