Repository OData/odata.net, pull requests merged in 2024-03, with the labels that each got.

#2860 [ODL 8]: Remove `HttpWebRequestMessage`
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/DataServiceRequestMessageFactory.cs
  src/Microsoft.OData.Client/Materialization/HttpWebResponseMessage.cs
  src/Microsoft.OData.Client/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/Serialization/HttpClientRequestMessage.cs
  src/Microsoft.OData.Client/Serialization/HttpWebRequestMessage.cs
  test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/CustomInstanceAnnotationsTests/ClientInstanceAnnotationsTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTests/IDReadLinkEditLinkTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTests/ODataWCFServiceQueryTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/PipelineEventsTests/PipelineEventsCrossPlatformAsyncTests.cs
  test/EndToEndTests/Tests/Client/Build.Desktop/TransportLayerTests/HttpClientRequestMessage.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/DollarFilterWithCastTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceContextHttpClientHandlerProviderTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/TestHttpWebRequestMessage.cs
  test/FunctionalTests/Taupo/Source/Taupo.Astoria/Client/DataServiceContextHttpTracker.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/HttpWebRequestUnitTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/RequestInfoTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/BuildingRequestEventFunctionalTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ReceivingResponseFunctionalTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/TestHookConsumer.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientExtensions/DataServiceContextWithStreamCustomizer.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/MediaStreaming.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/StateChange.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/UpdateTests.vb
Labels: Extra Large

#2870 [ODL 8]: Merge JsonReader interfaces into one
  src/Microsoft.OData.Core/Json/BufferingJsonReader.cs
  src/Microsoft.OData.Core/Json/IJsonReader.cs
  src/Microsoft.OData.Core/Json/IJsonReaderAsync.cs
  src/Microsoft.OData.Core/Json/IJsonReaderFactoryAsync.cs
  src/Microsoft.OData.Core/Json/IJsonStreamReader.cs
  src/Microsoft.OData.Core/Json/IJsonStreamReaderAsync.cs
  src/Microsoft.OData.Core/Json/IODataJsonOperationsDeserializerContext.cs
  src/Microsoft.OData.Core/Json/JsonReader.cs
  src/Microsoft.OData.Core/Json/JsonReaderExtensions.cs
  src/Microsoft.OData.Core/Json/ODataJsonReaderCoreUtils.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchBodyContentReaderStream.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchPayloadItemPropertiesCache.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ReorderingJsonReader.cs
  src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/JsonReaderAssertions.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeserializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/BinaryValueEncodingTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonReaderWriterInjectionTests.cs
Labels: Extra Large

#2874 IJsonWriterFactory.CreateJsonWriter method to accept Stream instead of TextWriter
  src/Microsoft.OData.Core/Json/DefaultJsonWriterFactory.cs
  src/Microsoft.OData.Core/Json/IJsonWriterFactory.cs
  src/Microsoft.OData.Core/Json/IStreamBasedJsonWriterFactory.cs
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriterFactory.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/Uri/ODataUriConversionUtils.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonLightInstanceAnnotationWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockJsonWriterFactory.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockJsonWriterFactoryWrapper.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactory.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterFactoryAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterFactoryTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/SingletonBatchRoundtripJsonLightTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonReaderWriterInjectionTests.cs
Labels: Large

#2872 [ODL 8]: Merge `SimplifiedODataOptions` into relevant reader, writer and URI parser settings classes.
  src/Microsoft.OData.Core/ContainerBuilderExtensions.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightInputContext.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
  src/Microsoft.OData.Core/ODataInputContext.cs
  src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
  src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
  src/Microsoft.OData.Core/ODataOutputContext.cs
  src/Microsoft.OData.Core/ODataSimplifiedOptions.cs
  src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/Uri/ODataUrlKeyDelimiter.cs
  src/Microsoft.OData.Core/UriParser/ODataUriParserConfiguration.cs
  src/Microsoft.OData.Core/UriParser/ODataUriParserSettings.cs
  test/EndToEndTests/Services/ODataDefaultService/DefaultWCFSvcDataSource.cs
  test/EndToEndTests/Services/ODataSimplifiedService/ODataSimplifiedDataSource.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/FeedAnnotationIntegrationTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/InstanceAnnotationsReaderIntegrationTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/ODataJsonLightReaderIntegrationTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Writer/InstanceAnnotationWriterIntegrationTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataSimplifiedOptionsTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageReaderSettingsTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterSettingsTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Reader/JsonLight/ODataJsonLightSingletonReaderTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonReaderWriterInjectionTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/JsonLight/AutoGeneratedUrlsShouldPutKeyValueInDedicatedSegmentTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParseSettingsTests.cs
Labels: Extra Large

#2883 Allow custom `HttpClient` via `IHttpClientFactory`
  src/Microsoft.OData.Client/DataServiceClientFormat.cs
  src/Microsoft.OData.Client/DataServiceClientRequestMessageArgs.cs
  src/Microsoft.OData.Client/DataServiceContext.cs
  src/Microsoft.OData.Client/IHttpClientHandlerProvider.cs
  src/Microsoft.OData.Client/InternalODataRequestMessage.cs
  src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
  src/Microsoft.OData.Client/ODataRequestMessageWrapper.cs
  src/Microsoft.OData.Client/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/RequestInfo.cs
  src/Microsoft.OData.Client/Serialization/DataServiceClientRequestMessage.cs
  src/Microsoft.OData.Client/Serialization/HttpClientRequestMessage.cs
  src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  test/Common/Microsoft.Test.OData.DependencyInjection/Microsoft.Test.OData.DependencyInjection.csproj
  test/FunctionalTests/Framework/Client/CLWrappers/WebDataContextWrapper.cs
  test/FunctionalTests/Framework/Models/QueriesModel.cs
  test/FunctionalTests/Framework/Models/UpdateModel.cs
  test/FunctionalTests/Framework/Workspaces/InMemoryWorkspaces/InMemoryWorkspace.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceContextHttpClientHandlerProviderTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/ODataMessageConcreteTypePreferHeaderTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/HttpClientRequestMessageTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/MockDelayedHttpClientHandler.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/MockHttpClientFactory.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/MockHttpClientHandler.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/MockHttpClientHandlerProvider.cs
  test/FunctionalTests/Microsoft.OData.TestCommon/Microsoft.OData.TestCommon.csproj
  test/FunctionalTests/Microsoft.OData.TestCommon/TestHttpClientFactory.cs
  test/FunctionalTests/Taupo/Source/Taupo.Astoria/Client/DataServiceContextCreator.cs
  test/FunctionalTests/Taupo/Source/Taupo.Astoria/Client/SendingRequestEventVerifier.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/DataServiceContextUtil.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/HeaderCollectionTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/HttpWebRequestUnitTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/LinqTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientExtensions/TestDataServiceClientRequestMessage.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/RegressionUnitTests/Tests/RegressionTest.cs
  test/FunctionalTests/Tests/DataServices/ddbasics/ClientBasics.cs
Labels: Extra Large

#2903 Fix E2E tests failure
  test/CommonAssemblies/Microsoft.VisualStudio.QualityTools.UnitTestFramework.10.0.0/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  test/CommonAssemblies/Microsoft.VisualStudio.QualityTools.UnitTestFramework.15.0.0/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  test/CommonAssemblies/Microsoft.VisualStudio.QualityTools.UnitTestFramework.17.0.0/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  test/EndToEndTests/Services/ServiceWrapperApp/ServiceWrapperApp.csproj
  test/EndToEndTests/Tests/Client/Build.Desktop/Microsoft.Test.OData.Tests.Client.csproj
Labels: Extra Small

#2910 Fix build errors in e2e tests
  test/EndToEndTests/Services/ODataSimplifiedService/ODataSimplifiedDataSource.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.PluggableFormat.Tests/Avro/Test/ODataAvroScenarioTests.cs
  test/FunctionalTests/Tests/DataOData/Tests/OData.PluggableFormat.Tests/VCard/Test/ODataVCardScenarioTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/MediaStreaming.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/StateChange.vb
  test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/UpdateTests.vb
Labels: Extra Small
