Repository OData/odata.net, pull requests merged in 2024-02, with the labels that each got.

#2782 Fix DeepInsert issue with matching RelatedDescriptors to NestedItems.…
  src/Microsoft.OData.Client/DeepInsertSaveResult.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DeepInsertE2ETests.cs
Labels: Large

#2846 Support writing large json base64 and string values
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
Labels: Medium

#2858 ODL 8.x - Deprecate support for JsonPCallback
  src/Microsoft.OData.Core/Json/IJsonWriter.cs
  src/Microsoft.OData.Core/Json/IJsonWriterAsync.cs
  src/Microsoft.OData.Core/Json/ODataJsonWriterUtils.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightSerializer.cs
  src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonWriterUtilsAsyncTests.cs
Labels: Small

#2859 Remove obsolete code
  src/Microsoft.OData.Client/DataServiceQueryOfT.cs
  src/Microsoft.OData.Client/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Client/QueryOperationResponse.cs
  src/Microsoft.OData.Client/QueryOperationResponseOfT.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.txt
  src/Microsoft.OData.Core/ODataMessageReader.cs
  src/Microsoft.OData.Core/ODataMessageWriter.cs
  src/Microsoft.OData.Core/ODataSimplifiedOptions.cs
  src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
  src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/UriParser/Aggregation/AggregateToken.cs
  src/Microsoft.OData.Core/UriParser/Aggregation/AggregateTransformationNode.cs
  src/Microsoft.OData.Edm/PublicAPI/net48/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Edm/Validation/ValidationRuleSet.cs
  src/Microsoft.OData.Edm/Validation/ValidationRules.cs
  test/EndToEndTests/Services/ODataWCFLibrary/Handlers/DeltaHandler.cs
  test/EndToEndTests/Services/ODataWCFLibrary/Handlers/DeltaLinkHandler.cs
  test/EndToEndTests/Services/ODataWCFLibrary/ResponseWriter.cs
  test/FunctionalTests/Framework/Features/Pipeline/PipelineWorkspaces.cs
  test/FunctionalTests/Framework/ReflectionCodeGeneration/ProviderWrapperGenerator.cs
  test/FunctionalTests/Framework/Verification/APICallLogBuilder.cs
  test/FunctionalTests/Framework/Workspaces/APICallLog.cs
  test/FunctionalTests/Framework/Workspaces/ProviderWrappers.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRuleSetTests.cs
  test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRulesTests.cs
  test/FunctionalTests/Service/Microsoft.OData.Service.csproj
  test/FunctionalTests/Service/Microsoft/OData/Service/IExpandProvider.cs
  test/FunctionalTests/Service/Microsoft/OData/Service/Providers/ExpressionEvaluator.cs
  test/FunctionalTests/Service/Microsoft/OData/Service/RequestQueryProcessor.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Stubs/DataServiceProvider/DSPDataService.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Stubs/DataServiceProvider/DSPExpandProvider.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/ProviderTests.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/QueryTest.cs
  test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/SelectTest.cs
Labels: Large

#2866 [ODL 8]: Deprecate `KeyComparisonGeneratesFilterQuery` and set default to `true`.
  src/Microsoft.OData.Client/DataServiceContext.cs
  test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
  test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceContextTests.cs
Labels: Extra Small

#2868 Default leaveOpen to false in ODataBinaryStreamValue constructor
  src/Microsoft.OData.Core/Value/ODataBinaryStreamValue.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedSerializerUndecalredTests.cs
Labels: Extra Small

#2877 Create test cases and benchmarks for writing large json base64 and st…
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/ExpectedOutput.txt
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/ExperimentTests.csproj
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/WriterTests.cs
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/Benchmarks.cs
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/JsonWriterBenchmarks.csproj
  test/PerformanceTests/SerializationComparisonsTests/Lib/CustomerDataSet.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/DataModel.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/DefaultWriterCollection.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ExperimentsLib.csproj
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterAsyncDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterAsyncPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriterWithArrayPool.cs
  test/PerformanceTests/SerializationComparisonsTests/README.md
  test/PerformanceTests/SerializationComparisonsTests/TestServer/Controllers/CustomersController.cs
  test/PerformanceTests/SerializationComparisonsTests/TestServer/TestServer.csproj
Labels: Extra Large

#2873 Support writing large json base64 and string values (#2846)
  src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
Labels: Medium
