Repository OData/odata.net, pull requests merged in 2024-01, with the labels that each got.

#2834 Fix memory regression in DuplicatePropertyNameChecker
  src/Microsoft.OData.Core/DuplicatePropertyNameChecker.cs
  src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
  src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
  src/Microsoft.OData.Core/WriterValidator.cs
Labels: Extra Small

#2830 Fixes #2829: support built-in function in $orderby.
  test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FullUriFunctionalTests.cs
Labels: Extra Small

#2812 Add flag to skip property verification in `ODataResource`
  src/Microsoft.OData.Core/ODataResource.cs
  src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
  src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  test/FunctionalTests/Microsoft.OData.Core.Tests/ODataResourceTests.cs
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
  test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Labels: Extra Small

#2847 Rename master to main
  README.md
  azure-pipelines-nightly.yml
  azure-pipelines-rolling.yml
  benchmarks.yml
  tools/Release/CreateAndPushBranch.ps1
Labels: Extra Small

#2850 Add dev-8.x branch to pipeline trigger
  README.md
  azure-pipelines-nightly.yml
  azure-pipelines-rolling.yml
Labels: Extra Small

#2835 Optimize `ODataPath` operations
  src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
  src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
  src/Microsoft.OData.Core/ODataWriterCore.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/KeySegment.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs
  src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs
  src/Microsoft.OData.Core/UriParser/Visitors/SplitEndingSegmentOfTypeHandler.cs
  src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathExtensionsTests.cs
Labels: Large

#2849 Create test cases and benchmarks for writing large json base64 and string values
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
  test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/ExpectedOutput.txt
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/ExperimentTests.csproj
  test/PerformanceTests/SerializationComparisonsTests/ExperimentTests/WriterTests.cs
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/Benchmarks.cs
  test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/JsonWriterBenchmarks.csproj
  test/PerformanceTests/SerializationComparisonsTests/Lib/CustomerDataSet.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/DataModel.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/DefaultWriterCollection.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ExperimentsLib.csproj
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterAsyncDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterAsyncPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriter.cs
  test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriterWithArrayPool.cs
  test/PerformanceTests/SerializationComparisonsTests/README.md
  test/PerformanceTests/SerializationComparisonsTests/TestServer/Controllers/CustomersController.cs
  test/PerformanceTests/SerializationComparisonsTests/TestServer/TestServer.csproj
Labels: Extra Large
